### ISSUE TITLE
Inconsistent use of build-rs in tutorial

### ISSUE THREAD

**Issue by camio** [HKalbasi/zngur#11]
The tutorial includes this line in the Cargo.toml file:

```toml
[build-dependencies]
#...
build-rs = "0.1.2" # This one is optional
#...
```

Then, `build.rs` uses that module in some places, but omits it in other places:

```rust
fn main() {
    build::rerun_if_changed("main.zng"); # Used here
  
    # Not used here, but this could be simplified to `let crate_dir = build::cargo_manifest_dir()` 
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    # ...
}
```

From the perspective of someone following the tutorial, it would be smoother if build-rs were used consistently, my preference, or not at all.
